language: java

matrix:
   include:
      - jdk: openjdk8
        env: 
           - ADDITIONAL_MAVEN_ARGS="-P enable-jacoco"  # -P enable-mutation-testing

install: true

cache:
   directories:
      - $HOME/.m2

script:
   - mvn -f db-test-aggregator/pom.xml clean verify $ADDITIONAL_MAVEN_ARGS coveralls:report

