language: java

matrix:
   include:
      # always build this environment
      - jdk: openjdk8
        env: 
           - ADDITIONAL_MAVEN_ARGS="-P enable-jacoco -P enable-mutation-testing"
           - ADDITIONAL_MAVEN_ARGS=""

# skip installation step
install: true

cache:
   directories:
      - $HOME/.m2

script:
   - mvn -f db-test-parent/pom.xml clean verify $ADDITIONAL_MAVEN_ARGS